services:
  traefik:
    image: traefik:v3.7
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=proxy
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy

  auth:
    image: ${CAPITLY_AUTH_IMAGE}
    restart: unless-stopped
    env_file:
      - auth.env
      - auth-shared.env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.auth.rule=PathPrefix(`/auth`)"
      - "traefik.http.routers.auth.priority=100"
      - "traefik.http.middlewares.auth-strip.stripprefix.prefixes=/auth"
      - "traefik.http.routers.auth.middlewares=auth-strip"
      - "traefik.http.services.auth.loadbalancer.server.port=${AUTH_SERVER_PORT}"
    depends_on:
      postgres_auth:
        condition: service_healthy
    networks:
      - auth
      - proxy

  postgres_auth:
    image: postgres:18-bookworm
    restart: unless-stopped
    env_file:
      - auth-shared.env
    volumes:
      - postgres_auth_data_prod:/var/lib/postgresql/
    networks:
      - auth
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  frontend:
    image: nginx:alpine
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.priority=1"
      - "traefik.http.services.frontend.loadbalancer.server.port=${FRONTEND_SERVER_PORT}"
    networks:
      - proxy

  core:
    image: traefik/whoami
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.core.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.core.priority=100"
      - "traefik.http.services.core.loadbalancer.server.port=${CORE_SERVER_PORT}"
    depends_on:
      postgres_core:
        condition: service_healthy
    networks:
      - core
      - proxy

  postgres_core:
    image: postgres:18-bookworm
    restart: unless-stopped
    environment:
      POSTGRES_DB: capitly_core # todo: rework with core docker issue
      POSTGRES_USER: dev #
      POSTGRES_PASSWORD: dev_password #
    volumes:
      - postgres_core_data_prod:/var/lib/postgresql/
    networks:
      - core
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d capitly_core"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

networks:
  proxy:
    name: proxy
  auth:
  core:

volumes:
  postgres_auth_data_prod:
  postgres_core_data_prod: