FROM eclipse-temurin:25-jdk AS builder

WORKDIR /app
RUN apt-get update && apt-get install -y maven && rm -rf /var/lib/apt/lists/*

COPY . /app
RUN mvn -f /app/pom.xml -pl core -am -DskipTests clean package

FROM eclipse-temurin:25-jre
WORKDIR /app

RUN adduser --system core_officer

COPY --from=builder /app/core/target/capitly-core-0.0.0-dev.jar /app/app.jar

RUN chown core_officer /app/app.jar

USER core_officer

EXPOSE 8081
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
