@startuml System_Diagramm_High-Level

actor "User / Browser" as User

package Frontend #DFF7DF{
    component "Vite Svelte Frontend" as svelte
}

package Backend {
    package "core (modularer Monolith)" as capitly.core #DFF7DF { 
        component Feature1
        component Feature...
    }

    package "Auth Service (microservice)" as capitly.Auth #ADD8E6
    package "ML Service (microservice)" as capitly.ML #DFF7DF

    capitly.core ..> capitly.ML : async jobs / events (Kafka/Queue)
    capitly.core --> capitly.Auth : JWT validation (JWKS fetch HTTPS)
}

package Datastores {
    database "PostgreSQL_core\n(prod) / H2 (dev)" as PG_core #DFF7DF
    database "PostgreSQL_auth" as PG_auth #ADD8E6
    database "InfluxDB (time-series)" as INFLUX #DFF7DF
    component "Valkey (cache)" as VALKEY #DFF7DF
}

capitly.core ---> PG_core : owns / JDBC / SQL
capitly.core ---> VALKEY : Cache read/write (TCP/Redis-like)
capitly.core ---> INFLUX : Influx write/query (HTTP / line-protocol)
capitly.Auth ---> PG_auth : owns / JDBC / SQL

package External {
    component "External Finance API" as FINAPI
}


User --> svelte
svelte --> capitly.core : REST (HTTPS / JSON)
svelte --> capitly.Auth : OIDC / OAuth2 (HTTPS)

capitly.core -> FINAPI : REST (HTTPS / JSON)\n(rate‑limited, cached)
' Legend
package Legend {
    component "Auth Docker Network" as legendAuth #ADD8E6
    component "Core Docker Network" as legendCore #DFF7DF
}

@enduml