FROM eclipse-temurin:25-jdk AS builder

WORKDIR /app
RUN apt-get update && apt-get install -y maven && rm -rf /var/lib/apt/lists/*

COPY . /app
RUN mvn -f /app/pom.xml -pl auth -am -DskipTests clean package

FROM eclipse-temurin:25-jre
WORKDIR /app

RUN adduser --system auth_officer

COPY --from=builder /app/auth/target/capitly-auth-0.0.0-dev.jar /app/app.jar

RUN chown auth_officer /app/app.jar

USER auth_officer

EXPOSE 8081
ENTRYPOINT ["java", "-jar", "/app/app.jar"]